package com.pdp.ticket.model;

public enum BotState {
      SHARE_CONTACT,
      ADMIN_MENU,
      BUS_MENU,
      BUS_SHOW_BUS,
      BUS_ADD_NAME,
      BUS_ADD_NUMBER,
      BUS_ADD_SEAT,
      DESTINATION_MENU,
      DESTINATION_ADD_NAME,
      DESTINATION_SHOW_DESTINATION,
      TRAVEL_MENU,
      TRAVEL_ADD_FROM,
      TRAVEL_ADD_TO,
      TRAVEL_ADD_DEPARTURE_TIME,
      TRAVEL_ADD_ARRIVAL_TIME,
      TRAVEL_ADD_BUS,
      TRAVEL_ADD_PRICE_FOR_PER_SEAT,
      TRAVEL_ADD_CREATED_TIME,

      ADMIN_DRIVER_MENU,
      ADMIN_TRAVEL_MENU,
      ADMIN_DESTINATION_MENU,
      USER_MENU,
      CHOSE_FROM_DESTINATION,
      CHOSE_TO_DESTINATION,
      CHOOSE_TRAVEL,
      CHOOSE_TICKET,
      ADD_PASSENGER,
      PAYMENT

}
